### ISSUE TITLE
files don't exist

### ISSUE THREAD

**Issue by abhi-at-bitsy** [formio/pdf-libs#26]
https://form.io/pdf/dist/formio.pdf.min.js

https://form.io/pdf/dist/formio-pdf.min.css

**Comment by abhi-at-bitsy** [comment]
@AlexeyNikipelau so I am running the docker image locally to convert pdf to html using this service, and the output html has 

#############
# Do not modify
"""
</body>
<script src="https://form.io/pdf/dist/formio-pdf.min.js"></script>
<script src="https://unpkg.com/seamless@latest/build/seamless.child.min.js"></script>
</html>
"""

# MANIFEST END

but https://form.io/pdf/dist/formio-pdf.min.js doesn't exists.
so does https://form.io/pdf/dist/formio-pdf.min.css

**Comment by abhi-at-bitsy** [comment]
when I create a pdf form from your website they have inline js files at the bottom, formio-pdf and formio-premium

**Comment by abhi-at-bitsy** [comment]
@AlexeyNikipelau  @lane-formio @brendanbond can you please check this? what's the latest pdf and css paths?

**Comment by abhi-at-bitsy** [comment]
@AlexeyNikipelau @lane-formio @brendanbond any updates?

**Comment by abhi-at-bitsy** [comment]
use case is simple, I am generating pdf to html so that I can give it to formio pdf viewer.

**Comment by abhi-at-bitsy** [comment]
@AlexeyNikipelau any updates?

**Comment by lane-formio** [comment]
It seems that what you are trying to accomplish here is something that we offer exclusively as part of our enterprise offering to convert formio form submissions to a pdf output.

Can you be more specific about what you are trying to achieve?

**Comment by abhi-at-bitsy** [comment]
no, I am not trying to convert form submissions to pdf output.

I am trying to create a service which we will host on our own infra, AWS lambda mostly.
When users upload a pdf on our platform, we will call /convertohtml endpoint of this service in the express app.

then upload the generated html on our s3, and give that url to formio-viewer.

```
const initialFormFields = {
  display: 'pdf',
  settings: {
    pdf: {
      id: '1ec0f8ee-6685-5d98-a847-26f67b67d6f0',
      src: 'https://ourcdn.com/pdf',
    },
  },
};```

**Comment by abhi-at-bitsy** [comment]
@AlexeyNikipelau so the problem is this repo is trying to add those files to the generated html file, but don't exist.
I tried the same via form.io, you are adding seamless and formio.pdf.min.js inline to the generated html.

**Comment by brendanbond** [comment]
@abhi-at-bitsy this library is essentially an open-source wrapper around the `pdf2htmlEX` binary, but it doesn't include the ability to actually use the @formio/js form renderer in PDFs. That ability uses private, closed source code that we inline into the PDF itself. If you're interested in a license, please contact sales@form.io and they'd be happy to help you out.

**Comment by abhi-at-bitsy** [comment]
we want to remain open source, so if you can please help making these two available?


https://form.io/pdf/dist/formio.pdf.min.js

https://form.io/pdf/dist/formio-pdf.min.css

**Comment by brendanbond** [comment]
As I mentioned, the ability to generate and render PDF forms is a closed source product that we sell. We're not going to make those available without a license.
