### ISSUE TITLE
Timeout values from environment variables cause "unsigned integer" error in HTML generation configuration

### ISSUE THREAD

**Issue by fless-lab** [formio/pdf-libs#29]
The application fails to handle non-integer values for `HTML_GENERATION_TIMEOUT` and `HTML_GENERATION_BACKOFF` environment variables, resulting in a "timeout out of range" error. This issue affects configurations where these environment variables are set to values that may be mistakenly interpreted as non-integer (e.g., string format), causing a 500 Internal Server Error during PDF to HTML conversion.

**Steps to reproduce :**
1. Set the environment variables `HTML_GENERATION_TIMEOUT` and `HTML_GENERATION_BACKOFF` to values without parsing them as integers (e.g., as a string in `.env`).
2. Start the application and attempt to convert a PDF to HTML via the `/convertToHtml` endpoint.
3. Observe the error message indicating that the "timeout" value is out of range.

**What we want :**
The application should properly parse `HTML_GENERATION_TIMEOUT` and `HTML_GENERATION_BACKOFF` as integers to avoid out-of-range errors. If a non-integer value is provided, the application could fallback to a default or raise a validation error.

**What we have :**
The application throws a 500 Internal Server Error, with an error message stating: "The value of 'timeout' is out of range. It must be an unsigned integer."

**Environnement :**
- OS: Ubuntu 22.04
- Node.js version: 20
- Application configuration: [Détails pertinents de votre configuration d'application]

**Solution :**
Ensure that `HTML_GENERATION_TIMEOUT` and `HTML_GENERATION_BACKOFF` environment variables are parsed as integers. This can be achieved by modifying the configuration in the `config.js`

**Comment by lane-formio** [comment]
<div>Agent Lane Doughtie unlinked Freshdesk ticket <a href="https://formhelp.freshdesk.com/a/tickets/51954">51954</a> from this issue.</div>
